#!/bin/awk -f
$1=="#qName"{next}
$2==0 && $3==0 && $4==0 && $5==0{print $1, "ancient" }
$2!=0 && $3==0 && $4==0         {print $1 , "dog" }
$2!=0 && $3!=0 && $4==0 && $5==0{print $1 , "mouse" }
            $3!=0 && $4!=0 && $5==0{print $1 , "rhesus" }
                  $4!=0 && $5!=0{print $1 , "chimp" }
