#!/bin/bash
# splitRetrosByAge input.bed ancient.bed recent.bed
# mouseNet column 32, dogNet column 54, rhesusNet column 31
tawk '{ortho=($32+$54)/2}ortho<10{print $0}' $1 |sort -k5,5nr> $2
tawk '{ortho=($32+$54)/2}ortho>=10{print $0}' $1 |sort -k5,5nr> $3
