ROOT = ..
SHELL = /bin/bash
db=hg18
ncbiBuild=36.3
retroDate=20081004
set=2008-10-04
synOrgs = canFam2 mm9 panTro2 rheMac2 rn4

include ${ROOT}/rules/defs.mk

all: mrnaGet mrnaAlign 

include ${ROOT}/rules/mrnaAlign.mk
include ${ROOT}/rules/mrnaGet.mk
