#!/bin/bash

set -beEu -o pipefail
tawk '$5>500{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$15}' $1 |sort> tmp.$$.bed 
bedOverlap tmp.$$.bed tmp2.$$.bed 
cut -f 2-6,14 tmp2.$$.bed |sort> $2
rm -f tmp.$$.bed tmp2.$$.bed
