#!/bin/bash
# splitRetrosByAge ucscRetroInfo.bed ucscRetroOrtho.bed ancient.bed recent.bed net1 net2
set -bveEu -o pipefail
if [ $BASH_ARGC ]; then
       echo "Checking for nets  $5 and $6 for ancient retros "
else
       echo "usage $0 ucscRetroInfo.bed ucscRetroOrtho.bed ancient.bed recent.bed net1 net2 scriptdir"
       exit 3
fi
RETRO=$1
ORTHO=$2
ANCIENTOUT=$3
RECENTOUT=$4
NET1=$5
NET2=$6
SCRIPT=$7
join -o 1.1 1.2 1.3 2.2 2.3  $ORTHO $ORTHO|awk -v n1=$NET1 -v n2=$NET2 '$2==n1 && $4==n2 && $3==0 && $5==0 {print $1}' > ortho.ancient.id
$SCRIPT/selectById -tsv 1 ortho.ancient.id 4 $RETRO |sort -k5,5nr> ${ANCIENTOUT}
$SCRIPT/selectById -not -tsv 1 ortho.ancient.id 4 $RETRO |sort -k5,5nr> ${RECENTOUT}
